title: Shane Kennedy
logo: /Images/headpic.jpg
description: Hi, my name is Shane Kennnedy, if you wish to find out more about my experience and skills, view my LinkedIn Profile <a href="https://www.linkedin.com/in/shane-kennedy-8b6a74251/"> here.</a>
#show_downloads: true
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
