title: ML Portfolio
logo: /Images/headpic.jpg
description: *If you wish to find out more about my experience and skills, view my LinkedIn Profile [here.](https://www.linkedin.com/in/shane-kennedy-8b6a74251/)*
#show_downloads: true
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
